[package]
name = "pa"
version = "0.1.0"
authors = ["geekskick <geeks_kick@yahoo.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portaudio = "0.7.0"
three="0.4.0"