[package]
name = "itertools"
version = "0.1.0"
authors = ["geekskick <geeks_kick@yahoo.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
textplots = "0.5.1"
num = "0.2.1"